USE IMPACTA

CREATE TABLE USUARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER VARCHAR(50),
    EMAIL VARCHAR (50),
    DT_INSERT DATETIME
);

INSERT INTO USUARIO VALUES(NULL,'GCONCEICAO', 'gabriel@email.com',now());
INSERT INTO USUARIO VALUES(NULL,'IMPACTA', 'impacta@email.com',now());

